src/Entity/MediaType.php
<?php

namespace App\Entity;

use App\Entity\Media;
use App\Repository\MediaTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MediaTypeRepository::class)
 */
class MediaType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $borrow_duration;

    /**
     * @ORM\OneToMany(targetEntity=Media::class, mappedBy="media_type")
     */
    private $medias;

    public function __construct()
    {
        $this->medias = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBorrowDuration(): ?int
    {
        return $this->borrow_duration;
    }

    public function setBorrowDuration(int $borrow_duration): self
    {
        $this->borrow_duration = $borrow_duration;

        return $this;
    }

    /**
     * @return Collection|Media[]
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): self
    {
        if (!$this->medias->contains($media)) {
            $this->medias[] = $media;
            $media->setMediaType($this);
        }

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        if ($this->medias->contains($media)) {
            $this->medias->removeElement($media);
            // set the owning side to null (unless already changed)
            if ($media->getMediaType() === $this) {
                $media->setMediaType(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }
}

src/Form/MediaTypeType.php
<?php

namespace App\Form;

use App\Entity\MediaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;


class MediaTypeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $nameOptions = [
            'label' => 'Type de média'
        ];
        $borrowDurationOptions = [
            'label' => 'Durée max. de l\'emprunt (en jours)'
        ];
        $builder
            ->add('name', TextType::class, $nameOptions)
            ->add('borrow_duration', NumberType::class, $borrowDurationOptions);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MediaType::class,
        ]);
    }
}

src/Controller/MediaTypeController.php
<?php

namespace App\Controller;

use App\Entity\MediaType;
use App\Form\MediaTypeType;
use App\Repository\MediaTypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MediaTypeController extends AbstractController
{
    /**
     * @Route("/list/media_type", name="media_type_index", methods={"GET"})
     */
    public function index(MediaTypeRepository $mediaTypeRepository): Response
    {
        return $this->render('media_type/index.html.twig', [
            'media_types' => $mediaTypeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/new/media_type", name="media_type_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $mediaType = new MediaType();
        $form = $this->createForm(MediaTypeType::class, $mediaType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($mediaType);
            $entityManager->flush();

            return $this->redirectToRoute('media_type_index');
        }

        return $this->render('media_type/new.html.twig', [
            'media_type' => $mediaType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/show/media_type/{id}", name="media_type_show", methods={"GET"})
     */
    public function show(MediaType $mediaType): Response
    {
        return $this->render('media_type/show.html.twig', [
            'media_type' => $mediaType,
        ]);
    }

    /**
     * @Route("/admin/edit/media_type/{id}", name="media_type_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, MediaType $mediaType): Response
    {
        $form = $this->createForm(MediaTypeType::class, $mediaType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('media_type_index');
        }

        return $this->render('media_type/edit.html.twig', [
            'media_type' => $mediaType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/delete/media_type/{id}", name="media_type_delete", methods={"DELETE"})
     */
    public function delete(Request $request, MediaType $mediaType): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mediaType->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($mediaType);
            $entityManager->flush();
        }

        return $this->redirectToRoute('media_type_index');
    }
}

templates/media_type/_delete_form.html.twig
<form method="post" action="{{ path('media_type_delete', {'id': media_type.id}) }}" onsubmit="return confirm('{{ 'Are you sure you want to delete this item?'|trans }}');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ media_type.id) }}">
    <button class="btn">{{ 'Delete'|trans }}</button>
</form>

templates/media_type/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save'|trans) }}</button>
{{ form_end(form) }}

templates/media_type/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit MediaType{% endblock %}

{% block body %}
    <h1>Edit MediaType</h1>

    {{ include('media_type/_form.html.twig', {'button_label': 'Update'|trans}) }}

    <a href="{{ path('media_type_index') }}">{{ 'back to list'|trans }}</a>

    {{ include('media_type/_delete_form.html.twig') }}
{% endblock %}

templates/media_type/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MediaType index{% endblock %}

{% block body %}
    <h1>MediaType index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Borrow_duration</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for media_type in media_types %}
            <tr>
                <td>{{ media_type.id }}</td>
                <td>{{ media_type.name }}</td>
                <td>{{ media_type.borrowDuration }}</td>
                <td>
                    <a href="{{ path('media_type_show', {'id': media_type.id}) }}">show</a>
                    <a href="{{ path('media_type_edit', {'id': media_type.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('media_type_new') }}">Create new</a>
{% endblock %}

templates/media_type/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New MediaType{% endblock %}

{% block body %}
    <h1>Create new MediaType</h1>

    {{ include('media_type/_form.html.twig') }}

    <a href="{{ path('media_type_index') }}">back to list</a>
{% endblock %}

templates/media_type/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}MediaType{% endblock %}

{% block body %}
    <h1>MediaType</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ media_type.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ media_type.name }}</td>
            </tr>
            <tr>
                <th>Borrow_duration</th>
                <td>{{ media_type.borrowDuration }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('media_type_index') }}">back to list</a>

    <a href="{{ path('media_type_edit', {'id': media_type.id}) }}">edit</a>

    {{ include('media_type/_delete_form.html.twig') }}
{% endblock %}