src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film extends Media
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $original_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="integer", nullable=true, nullable=true)
     * @Assert\Regex(
     * pattern="/\d/",
     * match=true,
     * message="Your name cannot contain a number"
     * )
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $director;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $actors;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOriginalTitle(): ?string
    {
        return $this->original_title;
    }

    public function setOriginalTitle(string $original_title): self
    {
        $this->original_title = $original_title;

        return $this;
    }

    public function getPublishDate(): ?\DateTimeInterface
    {
        return $this->publish_date;
    }

    public function setPublishDate(\DateTimeInterface $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(?string $director): self
    {
        $this->director = $director;

        return $this;
    }

    public function getActors(): ?string
    {
        return $this->actors;
    }

    public function setActors(string $actors): self
    {
        $this->actors = $actors;

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use App\Form\DigitalMediaType;
use App\Form\StockableMediaType;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('author')
            ->add('description')
            ->add('original_title')
            ->add('synopsis')
            ->add('duration')
            ->add('director')
            ->add('actors')
            ->add('DigitalMedia', DigitalMediaType::class)
            ->add('StockableMedia', StockableMediaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php
namespace App\Controller;
use App\Entity\Film;
use App\Entity\MediaType;
use App\Form\FilmType;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Entity\StockableMediaCopy as StockableMediaCopyService;

class FilmController extends AbstractController{

	/**
	 *
	 * @Route("/list/film", name="film_index", methods={"GET"})
	 */
	public function index(FilmRepository $filmRepository): Response{
		return $this->render('film/index.html.twig', [
			'films' => $filmRepository->findAll()
		]);
	}

	/**
	 *
	 * @Route("/admin/new/film", name="film_new", methods={"GET","POST"})
	 */
	public function new(Request $request, StockableMediaCopyService $stockableCopyService): Response{
		$film = new Film();
		$form = $this->createForm(FilmType::class, $film);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()){
			$film_media = $this->getDoctrine()
				->getRepository(MediaType::class)
				->findOneBy([
				'name' => 'Film'
			]);
			$film->setMediaType($film_media);
			$stockableCopyService->generateCopyFromMedia($film->getStockableMedia());

			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->persist($film);
			$entityManager->flush();

			$this->addFlash('success', 'Your new film were saved!');
			return $this->redirectToRoute('film_index');
		}

		if ($form->isSubmitted()){
			$this->addFlash('warning', 'Your new member is nat saved!');
		}

		return $this->render('film/new.html.twig', [
			'film' => $film,
			'form' => $form->createView()
		]);
	}

	/**
	 *
	 * @Route("/show/film/{id}", name="film_show", methods={"GET"})
	 */
	public function show(Film $film): Response{
		return $this->render('film/show.html.twig', [
			'film' => $film
		]);
	}

	/**
	 *
	 * @Route("/admin/edit/film/{id}", name="film_edit", methods={"GET","POST"})
	 */
	public function edit(Request $request, Film $film, StockableMediaCopyService $stockableCopyService): Response{
		$form = $this->createForm(FilmType::class, $film);
		$form->handleRequest($request);

		if ($form->isSubmitted()){
			if ($form->isValid()){
				try{
					$copyNumberFailedToBeRemoved = $stockableCopyService->handleMediaEdition($film);
					// Here, we can flush some data even if "$editSucceeded" is false (@see: function definition of "handleMediaEdition")
					$this->getDoctrine()
						->getManager()
						->flush();

					if (!$copyNumberFailedToBeRemoved){
						$this->addFlash('success', 'Données modifiées avec succès');
						return $this->redirectToRoute('film_index');
					} else{
						$this->addFlash('warning', sprintf('Attention, le système a détecté qu\'à partir de l\'exemplaire %d, le livre a été emprunté. Seuls les numéros d\'exemplaires au-dessus de ce numéro et n\'ayant jamais été emprunté seront supprimés', $copyNumberFailedToBeRemoved));
						$this->addFlash('notice', sprintf('Les données ont été partiellement mises à jour. Le nombre d\'exemplaires reste à %d', $copyNumberFailedToBeRemoved));
					}
				} catch (\Exception $ex){
					$this->addFlash('warning', 'Une erreur s\'est produite lors de l\'enregistrement');
					throw $ex;
				}
			} else{
				$this->addFlash('warning', 'Certaines informations saisies ne sont pas correctes');
			}
		}

		return $this->render('film/edit.html.twig', [
			'film' => $film,
			'form' => $form->createView()
		]);
	}

	/**
	 *
	 * @Route("/admin/delete/film/{id}", name="film_delete", methods={"DELETE"})
	 */
	public function delete(Request $request, Film $film): Response{
		if ($this->isCsrfTokenValid('delete' . $film->getId(), $request->request->get('_token'))){
			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->remove($film);
			$entityManager->flush();
		}

		return $this->redirectToRoute('film_index');
	}
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('film_delete', {'id': film.id}) }}" onsubmit="return confirm('{{ 'Are you sure you want to delete this film?'|trans }}');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn">{{ 'Delete'|trans }}</button>
</form>

templates/film/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save'|trans) }}</button>
{{ form_end(form) }}

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Edit Film'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Edit Film'|trans }}</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'|trans}) }}

    <a href="{{ path('film_index') }}">{{ 'back to list'|trans }}</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Film index'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Film index'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>{{ 'Title'|trans }}</th>
                <th>{{ 'Author'|trans }}</th>
                <th>Description</th>
                <th>Original_title</th>
                <th>Synopsis</th>
                <th>Duration</th>
                <th>Director</th>
                <th>Actors</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for film in films %}
            <tr>
                <td>{{ film.id }}</td>
                <td>{{ film.name }}</td>
                <td>{{ film.author }}</td>
                <td>{{ film.description }}</td>
                <td>{{ film.originalTitle }}</td>
                <td>{{ film.synopsis }}</td>
                <td>{{ film.duration }}</td>
                <td>{{ film.director }}</td>
                <td>{{ film.actors }}</td>
                <td>
                    <a href="{{ path('film_show', {'id': film.id}) }}">{{ 'show'|trans }}</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    |
                    <a href="{{ path('film_edit', {'id': film.id}) }}">{{ 'edit'|trans }}</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">{{ 'no records found'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

	{% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('film_new') }}">{{ 'register new film'|trans }}</a>
    {% endif %}
{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'register new film'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'register new film'|trans }}</h1>

    {{ include('film/_form.html.twig') }}

    <a href="{{ path('film_index') }}">{{ 'back to list'|trans }}</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Film'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Film'|trans }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ film.id }}</td>
            </tr>
            <tr>
                <th>{{ 'Title'|trans }}</th>
                <td>{{ film.name }}</td>
            </tr>
            <tr>
                <th>{{ 'Author'|trans }}</th>
                <td>{{ film.author }}</td>
            </tr>
            <tr>
                <th>{{ 'Description'|trans }}</th>
                <td>{{ film.description }}</td>
            </tr>
            <tr>
                <th>{{ 'Original_title'|trans }}</th>
                <td>{{ film.originalTitle }}</td>
            </tr>
            <tr>
                <th>{{ 'Synopsis'|trans }}</th>
                <td>{{ film.synopsis }}</td>
            </tr>
            <tr>
                <th>{{ 'Duration'|trans }}</th>
                <td>{{ film.duration }}</td>
            </tr>
            <tr>
                <th>{{ 'Director'|trans }}</th>
                <td>{{ film.director }}</td>
            </tr>
            <tr>
                <th>{{ 'Description'|trans }}Actors</th>
                <td>{{ film.actors }}</td>
            </tr>
        </tbody>
    </table>

	{% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('film_edit', {'id': film.id}) }}">{{ 'edit'|trans }}</a>

    {{ include('film/_delete_form.html.twig') }}
    {% else %}
 	<p>
 		Pour emprunter le support physique de ce média (livre papier, DVD film ou CD de musique), veuillez directement vous présenter à la médiathèque.<br>
		TODO: Dans le cas d'un ROLE_USER, on peut éventuellement rajouter un bouton "Emprunter " et/ou "Accéder au stream"
	</p>
	
    {% endif %}
    
    <a href="{{ path('film_index') }}">{{ 'back to list'|trans }}</a>

{% endblock %}