src/Entity/Borrow.php
<?php

namespace App\Entity;

use App\Repository\BorrowRepository;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

/**
 * @ORM\Entity(repositoryClass=BorrowRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Borrow
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Member::class, inversedBy="borrows")
     * @ORM\JoinColumn(nullable=false)
     */
    private $member;

    /**
     * @ORM\ManyToOne(targetEntity=StockableMediaCopy::class, inversedBy="borrows")
     * @ORM\JoinColumn(nullable=false)
     */
    private $stockable_media_copy;

    /**
     * @ORM\Column(type="datetime")
     */
    private $borrow_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expiry_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $return_date;

    /**
     * @ORM\ManyToOne(targetEntity=StateOfMedia::class)
     */
    private $return_media_state;

    
    public function __construct()
    {
    	$this->borrow_date = new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): self
    {
        $this->member = $member;

        return $this;
    }

    public function getStockableMediaCopy(): ?StockableMediaCopy
    {
        return $this->stockable_media_copy;
    }

    public function setStockableMediaCopy(?StockableMediaCopy $stockable_media_copy): self
    {
        $this->stockable_media_copy = $stockable_media_copy;

        return $this;
    }

    public function getBorrowDate(): ?\DateTimeInterface
    {
        return $this->borrow_date;
    }

    public function setBorrowDate(\DateTimeInterface $borrow_date): self
    {
        $this->borrow_date = $borrow_date;

        return $this;
    }


    public function getExpiryDate(): ?\DateTimeInterface
    {
        return $this->expiry_date;
    }

    public function setExpiryDate(\DateTimeInterface $expiry_date): self
    {
        $this->expiry_date = $expiry_date;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(?\DateTimeInterface $return_date): self
    {
        $this->return_date = $return_date;

        return $this;
    }

    public function getReturnMediaState(): ?StateOfMedia
    {
        return $this->return_media_state;
    }

    public function setReturnMediaState(?StateOfMedia $return_media_state): self
    {
        $this->return_media_state = $return_media_state;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function calculateExpiryDate(): self
    {
        // Expiry date must be pre-defined (on insert only) by the day numbers set to media type
        // e.g. if media type is book, and borrow duration is 30 days, then expiry date must be borrow date + 30 days

        // Get borrow duration
        $borrowDuration = $this->getStockableMediaCopy()->getStockableMedia()->getMedia()->getMediaType()->getBorrowDuration();
        $expiryDateTime = new \DateTime($this->getBorrowDate()->format('Y-m-d H:i'));
        $expiryDateTime->add(new \DateInterval("P${borrowDuration}D"));
        return $this->setExpiryDate($expiryDateTime);
    }

    public function __toString()
    {
        return $this->id;
    }

    public function getBorrowDuration() :Int
    {
        return $this->getStockableMediaCopy()
                        ->getStockableMedia()
                            ->getMedia()
                                ->getMediaType()
                                    ->getBorrowDuration();
    }
}

src/Entity/Media.php
<?php

namespace App\Entity;

use App\Repository\MediaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MediaRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="media_type_id", type="integer")
 * @ORM\DiscriminatorMap({"0" = "Media", "1" = "Book", "2" = "Film", "3" = "Music"})
 * @ORM\HasLifecycleCallbacks()
 */
class Media
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=500)
     * @Assert\NotBlank(message="Le titre ne doit pas être vide")
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    protected $author;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\ManyToOne(targetEntity=MediaType::class, inversedBy="medias")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $media_type;

    /**
     * @ORM\OneToOne(targetEntity=DigitalMedia::class, mappedBy="media", cascade={"persist", "remove"})
     */
    protected $digitalMedia;

    /**
     * @ORM\OneToOne(targetEntity=StockableMedia::class, mappedBy="media", cascade={"persist", "remove"})
     */
    protected $stockableMedia;
    
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMediaType(): ?MediaType
    {
        return $this->media_type;
    }

    public function setMediaType(?MediaType $media_type): self
    {
        $this->media_type = $media_type;

        return $this;
    }


    public function getDigitalMedia(): ?DigitalMedia
    {
        return $this->digitalMedia;
    }

    public function setDigitalMedia(DigitalMedia $digitalMedia): self
    {
        $this->digitalMedia = $digitalMedia;

        // set the owning side of the relation if necessary
        if ($digitalMedia->getMedia() !== $this) {
            $digitalMedia->setMedia($this);
        }

        return $this;
    }

    public function getStockableMedia(): ?StockableMedia
    {
        return $this->stockableMedia;
    }

    public function setStockableMedia(StockableMedia $stockableMedia): self
    {
        $this->stockableMedia = $stockableMedia;

        // set the owning side of the relation if necessary
        if ($stockableMedia->getMedia() !== $this) {
            $stockableMedia->setMedia($this);
        }

        return $this;
    }
    
    public function __toString(): string
    {
        return $this->name;
    }
}

src/Service/Entity/Borrow.php
<?php
namespace App\Service\Entity;
use App\Service\Entity as EntityService;
use App\Entity\Borrow as BorrowEntity;

/**
 * Attention! This could be confusing with the Borrow entity class placed into "src/Entity" folder
 *
 * @author fabriced
 *        
 */
class Borrow extends EntityService{

	/**
	 * Perform a full check
	 *
	 * @param BorrowEntity $borrowEntity
	 *        	Object to be checked
	 * @return boolean
	 */
	function fullCheck(BorrowEntity $borrowEntity){
		if (!$this->checkExpiryDateValidity($borrowEntity))
			return false;
		return true;
	}

	/**
	 * This will compare (borrow date + borrow duration) with expiry date.
	 * Note that, for borrow creation (new), expiry date is set on "prepersist" (look at "Borrow" entity class)
	 *
	 * @param BorrowEntity $borrowEntity
	 * @return boolean
	 */
	function checkExpiryDateValidity(BorrowEntity $borrowEntity){
		$borrowDuration = $borrowEntity->getBorrowDuration();
		$borrowDate = $borrowEntity->getBorrowDate();
		$expiryDate = $borrowEntity->getExpiryDate();
		// Calculate expected expiry date
		$expectedExpiryDate = new \DateTime(date('Y-m-d', $borrowDate->getTimestamp()));
		$expectedExpiryDate->add(new \DateInterval('P' . $borrowDuration . 'D'));
		if (!$expiryDate){
			$borrowEntity->setExpiryDate($expectedExpiryDate);
			return true;
		}
		if (date('Y-m-d', $expiryDate->getTimestamp()) != $expectedExpiryDate->format('Y-m-d'))
			return false;
		return true;
	}
}

src/Form/BorrowType.php
<?php
namespace App\Form;
use App\Entity\Borrow;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Repository\StockableMediaCopyRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\StockableMediaCopy;

class BorrowType extends AbstractType{

	/**
	 * @var \App\Repository\StockableMediaCopyRepository
	 */
	protected $stockableMediaCopyRepo;

	/**
	 * Inject instance of StockableMediaCopyRepository
	 *
	 * @param StockableMediaCopyRepository $stockableMediaCopyRepo
	 */
	public function __construct(StockableMediaCopyRepository $stockableMediaCopyRepo){
		$this->stockableMediaCopyRepo = $stockableMediaCopyRepo;
	}

	public function buildForm(FormBuilderInterface $builder, array $options){
		// Since this form type is used in "edit" borrow form, then, will take loaded data from borrow object
		/**
		 * @var \App\Entity\Borrow
		 */
		$borrow = is_a($options['data'], Borrow::class) ? $options['data'] : new Borrow();
		// Passing "stockableMediaCopyRepo" property into variable to be able to "use" it in the "closure" function
		$stockableMediaCopyRepo = $this->stockableMediaCopyRepo;
		$queryBuilder = function () use ($stockableMediaCopyRepo, $borrow){
			return $stockableMediaCopyRepo->findAllAvailable(\Doctrine\ORM\QueryBuilder::class, $borrow->getStockableMediaCopy()->getId());
		};
		
		$builder->add('borrow_date', DateType::class, [
				'widget' => 'single_text',
				'html5' => true,
				'label' => "Date de l'emprunt"
			])
			->add('expiry_date', DateType::class, [
				'widget' => 'single_text',
				'html5' => true,
				'label' => 'À restituer avant le',
				'attr' => [
					'readonly' => true // This field is not manually updatable, but calculated
				]
			])
			->add('member', null, [
				'label' => 'Adhérent'
			])
			->add('stockable_media_copy', EntityType::class, [
				'class' => StockableMediaCopy::class,
				'label' => 'Exemplaire emprunté',
				// Closure function using property "stockableMediaCopyRepo"
				'query_builder' => $queryBuilder
			])
			->add('return_date', DateType::class, [
				'widget' => 'single_text',
				'label' => 'Restitué le',
				'html5' => true,
				'required' => false
			])
			->add('return_media_state', null, [
				'label' => 'État de l\'exemplaire après restitution'
			]);
	}

	public function configureOptions(OptionsResolver $resolver){
		$resolver->setDefaults([
			'data_class' => Borrow::class
		]);
	}
}

src/Controller/BorrowController.php
<?php
namespace App\Controller;
use App\Entity\Borrow;
use App\Form\BorrowType;
use App\Form\BorrowNewType;
use App\Repository\BorrowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\Entity\Borrow as BorrowService;

class BorrowController extends AbstractController{

	/**
	 *
	 * @Route("/admin/list/borrow", name="borrow_index", methods={"GET"})
	 */
	public function index(BorrowRepository $borrowRepository): Response{
		return $this->render('borrow/index.html.twig', [
			'borrows' => $borrowRepository->findAll()
		]);
	}

	/**
	 *
	 * @Route("/admin/new/borrow", name="borrow_new", methods={"GET","POST"})
	 */
	public function new(Request $request): Response{
		$borrow = new Borrow();
		$form = $this->createForm(BorrowNewType::class, $borrow);
		$form->handleRequest($request);

		if ($form->isSubmitted()){
			if ($form->isValid()){
				try{
					$entityManager = $this->getDoctrine()->getManager();
					$entityManager->persist($borrow);
					$entityManager->flush();
		
					$this->addFlash('success', 'Données enregistrées avec succès');
					return $this->redirectToRoute('borrow_index');
				}catch(\Exception $ex){
					$this->addFlash('error', 'Une erreur est survenue lors de la création des données');
					throw $ex;
				}
			}else{
				$this->addFlash('warning', '');
			}
		}

		return $this->render('borrow/new.html.twig', [
			'borrow' => $borrow,
			'form' => $form->createView()
		]);
	}

	/**
	 *
	 * @Route("/admin/show/borrow/{id}", name="borrow_show", methods={"GET"})
	 */
	public function show(Borrow $borrow): Response{
		return $this->render('borrow/show.html.twig', [
			'borrow' => $borrow
		]);
	}

	/**
	 *
	 * @Route("/admin/edit/borrow/{id}/edit", name="borrow_edit", methods={"GET","POST"})
	 */
	public function edit(Request $request, Borrow $borrow, BorrowService $borrowService): Response{
		$form = $this->createForm(BorrowType::class, $borrow);
		$form->handleRequest($request);
		$borrow_duration = $borrow->getBorrowDuration();
		if ($form->isSubmitted()){
			if ($form->isValid()){
				try{
					$redirectToList = true;
					if (!$borrowService->checkExpiryDateValidity($borrow)){
						$this->addFlash(
							'warning',
							sprintf("Les données ont été enregistrées, mais la date d'échéance du prêt n'est pas %d jour(s) après la date d'emprunt (durée normalement prédéfinie pour tous les types de médias : %s",
								$borrow->getBorrowDuration(),
								$borrow->getStockableMediaCopy()
									->getStockableMedia()
									->getMedia()
									->getMediaType()
									->getName()
							)
						);
						$redirectToList = false;
					}
					$this->getDoctrine()->getManager()->flush();
		
					$this->addFlash('success', 'Données modifiées avec succès');
					if ($redirectToList)
						return $this->redirectToRoute('borrow_index');
				}catch(\Exception $ex){
					$this->addFlash('error', 'Une erreur est survenue lors du traitement des données');
					throw $ex;
				}
			}else{
				$this->addFlash('warning', 'Certaines informations sont invalides');
			}
		}

		return $this->render('borrow/edit.html.twig', [
			'borrow' => $borrow,
			'form' => $form->createView(),
			'borrow_duration' => $borrow_duration
		]);
	}

	/**
	 *
	 * @Route("/admin/delete/borrow/{id}", name="borrow_delete", methods={"DELETE"})
	 */
	public function delete(Request $request, Borrow $borrow): Response{
		if ($this->isCsrfTokenValid('delete' . $borrow->getId(), $request->request->get('_token'))){
			$entityManager = $this->getDoctrine()->getManager();
			$entityManager->remove($borrow);
			$entityManager->flush();
			$this->addFlash('success', 'Données supprimées avec succès');
		}else{
			$this->addFlash('warning', 'Une erreur est survenue lors de la suppression des données');
		}

		return $this->redirectToRoute('borrow_index');
	}
}

templates/borrow/_delete_form.html.twig
<form method="post" action="{{ path('borrow_delete', {'id': borrow.id}) }}" onsubmit="return confirm('{{ 'Are you sure you want to delete this borrow?'|trans }}');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ borrow.id) }}">
    <button class="btn">{{ 'Delete'|trans }}</button>
</form>

templates/borrow/_form.html.twig
    {{ form_start(form) }}
    {{ form_widget(form) }}

    {% if borrow_duration is defined %}
      <input class="borrow_duration" type="hidden" value="{{borrow_duration}}"/>
    {% endif %}
    <button class="btn">{{ button_label|default('Save'|trans) }}</button>
    {{ form_end(form) }}

templates/borrow/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Edit Borrow'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Borrow #%d'|trans|replace({'%d': borrow.id}) }}</h1>
    
    {{ include('borrow/_form.html.twig', { button_label: 'Update'|trans , borrow_duration: borrow_duration })}}
    <a href="{{ path('borrow_index') }}">{{ 'back to list'|trans }}</a>
    {{ include('borrow/_delete_form.html.twig')   }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/EditBorow.js') }}"> </script>
{% endblock %}

templates/borrow/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Borrow index'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'Borrow index'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Catégorie</th>
                <th>{{ 'Title'|trans }}</th>
                <th>N° exemplaire</th>
                <th>Adhérent</th>
                <th>Date d'emprunt</th>
                <th>Échéance</th>
                <th>Restitué le</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for borrow in borrows %}
            <tr>
                <td>{{ borrow.stockableMediaCopy.stockableMedia.media.mediaType.name }}</td>
                <td>{{ borrow.stockableMediaCopy.stockableMedia.media.name }}</td>
                <td>{{ borrow.stockableMediaCopy.copyNumber }}/{{ borrow.stockableMediaCopy.stockableMedia.stock }}</td>
                <td>{{ borrow.member ? borrow.member.username : '' }}</td>
                <td>{{ borrow.borrowDate ? borrow.borrowDate|date('d/m/Y') : '' }}</td>
                <td>{{ borrow.expiryDate ? borrow.expiryDate|date('d/m/Y') : '' }}</td>
                <td>{{ borrow.returnDate ? borrow.returnDate|date('d/m/Y') : '' }}</td>
                <td>
                    <a href="{{ path('borrow_show', {'id': borrow.id}) }}">{{ 'show'|trans }}</a>
                    {% if is_granted('ROLE_BIBLIO') %}
                    |
                    <a href="{{ path('borrow_edit', {'id': borrow.id}) }}">{{ 'edit'|trans }}</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">{{ 'no records found'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('borrow_new') }}">{{ 'new borrow'|trans }}</a>
{% endblock %}

templates/borrow/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'New Borrow'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'New Borrow'|trans }}</h1>

    {{ include('borrow/_form.html.twig') }}

    <a href="{{ path('borrow_index') }}">{{ 'back to list'|trans }}</a>
{% endblock %}

templates/borrow/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Borrow'|trans }}{% endblock %}

{% block body %}
    <h1>Prêt {{ borrow.stockableMediaCopy.stockableMedia.media.mediaType.name|lower }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>N° enregistrement</th>
                <td>{{ borrow.id }}</td>
            </tr>
            <tr>
                <th>Adhérent</th>
                <td>{{ borrow.member ? borrow.member.username : '' }}</td>
            </tr>
            <tr>
                <th>Média</th>
                <td>{{ borrow.stockableMediaCopy.stockableMedia.media.name }}</td>
            </tr>
            <tr>
                <th>N° exemplaire</th>
                <td>{{ borrow.stockableMediaCopy.copyNumber }} (sur {{ borrow.stockableMediaCopy.stockableMedia.stock }} exemplaire(s))</td>
            </tr>
            <tr>
                <th>Date de l'emprunt</th>
                <td>{{ borrow.borrowDate ? borrow.borrowDate|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Échéance</th>
                <td>{{ borrow.expiryDate ? borrow.expiryDate|date('d/m/Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Restitué le</th>
                <td>{{ borrow.returnDate ? borrow.returnDate|date('d/m/Y H:i:s') : "en cours d'emprunt" }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('borrow_index') }}">{{ 'back to list'|trans }}</a>
    {% if is_granted('ROLE_BIBLIO') %}
	|
    <a href="{{ path('borrow_edit', {'id': borrow.id}) }}">{{ 'edit'|trans }}</a>

    {{ include('borrow/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}